apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: 'sd-test'
  labels: {}
  annotations: {}
  namespace: sd-test
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: sd-test.c-55821bf.kyma.ondemand.com
  service:
    name: sd-test
    port: 8080
  rules:
    - path: /.*
      methods:
        - GET
        - PUT
        - POST
        - DELETE
      accessStrategies:
        - handler: allow
