
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.namespaces.maintenancelookuptabledata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.DecimalDescriptor;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>com_sap_cloud_pricing_calculation_PriceConditionRange</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class com_sap_cloud_pricing_calculation_PriceConditionRange
    extends VdmComplex<com_sap_cloud_pricing_calculation_PriceConditionRange>
{

    @Getter
    private final java.lang.String odataType = "MaintenanceLookupTableDataService.com_sap_cloud_pricing_calculation_PriceConditionRange";
    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>type</b></p>
     * 
     * @return
     *     The type_2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("type")
    private java.lang.String type_2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange> TYPE_2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "type");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>value</b></p>
     * 
     * @return
     *     The value contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("value")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal value;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange> VALUE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "value");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>rateQuantity</b></p>
     * 
     * @return
     *     The rateQuantity contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("rateQuantity")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal rateQuantity;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange> RATE_QUANTITY = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "rateQuantity");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>rateQuantityUnit</b></p>
     * 
     * @return
     *     The rateQuantityUnit contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("rateQuantityUnit")
    private java.lang.String rateQuantityUnit;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange> RATE_QUANTITY_UNIT = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "rateQuantityUnit");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>upToValue</b></p>
     * 
     * @return
     *     The upToValue contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("upToValue")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal upToValue;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange> UP_TO_VALUE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "upToValue");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>upToUnit</b></p>
     * 
     * @return
     *     The upToUnit contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("upToUnit")
    private java.lang.String upToUnit;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange> UP_TO_UNIT = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<com_sap_cloud_pricing_calculation_PriceConditionRange>(com_sap_cloud_pricing_calculation_PriceConditionRange.class, "upToUnit");

    @Nonnull
    @Override
    public Class<com_sap_cloud_pricing_calculation_PriceConditionRange> getType() {
        return com_sap_cloud_pricing_calculation_PriceConditionRange.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("type", getType_2());
        values.put("value", getValue());
        values.put("rateQuantity", getRateQuantity());
        values.put("rateQuantityUnit", getRateQuantityUnit());
        values.put("upToValue", getUpToValue());
        values.put("upToUnit", getUpToUnit());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("type")) {
                final Object value = values.remove("type");
                if ((value == null)||(!value.equals(getType_2()))) {
                    setType_2(((java.lang.String) value));
                }
            }
            if (values.containsKey("value")) {
                final Object value = values.remove("value");
                if ((value == null)||(!value.equals(getValue()))) {
                    setValue(((BigDecimal) value));
                }
            }
            if (values.containsKey("rateQuantity")) {
                final Object value = values.remove("rateQuantity");
                if ((value == null)||(!value.equals(getRateQuantity()))) {
                    setRateQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("rateQuantityUnit")) {
                final Object value = values.remove("rateQuantityUnit");
                if ((value == null)||(!value.equals(getRateQuantityUnit()))) {
                    setRateQuantityUnit(((java.lang.String) value));
                }
            }
            if (values.containsKey("upToValue")) {
                final Object value = values.remove("upToValue");
                if ((value == null)||(!value.equals(getUpToValue()))) {
                    setUpToValue(((BigDecimal) value));
                }
            }
            if (values.containsKey("upToUnit")) {
                final Object value = values.remove("upToUnit");
                if ((value == null)||(!value.equals(getUpToUnit()))) {
                    setUpToUnit(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>type</b></p>
     * 
     * @param type_2
     *     The type_2 to set.
     */
    public void setType_2(
        @Nullable
        final java.lang.String type_2) {
        rememberChangedField("type", this.type_2);
        this.type_2 = type_2;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>value</b></p>
     * 
     * @param value
     *     The value to set.
     */
    public void setValue(
        @Nullable
        final BigDecimal value) {
        rememberChangedField("value", this.value);
        this.value = value;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>rateQuantity</b></p>
     * 
     * @param rateQuantity
     *     The rateQuantity to set.
     */
    public void setRateQuantity(
        @Nullable
        final BigDecimal rateQuantity) {
        rememberChangedField("rateQuantity", this.rateQuantity);
        this.rateQuantity = rateQuantity;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>rateQuantityUnit</b></p>
     * 
     * @param rateQuantityUnit
     *     The rateQuantityUnit to set.
     */
    public void setRateQuantityUnit(
        @Nullable
        final java.lang.String rateQuantityUnit) {
        rememberChangedField("rateQuantityUnit", this.rateQuantityUnit);
        this.rateQuantityUnit = rateQuantityUnit;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>upToValue</b></p>
     * 
     * @param upToValue
     *     The upToValue to set.
     */
    public void setUpToValue(
        @Nullable
        final BigDecimal upToValue) {
        rememberChangedField("upToValue", this.upToValue);
        this.upToValue = upToValue;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>upToUnit</b></p>
     * 
     * @param upToUnit
     *     The upToUnit to set.
     */
    public void setUpToUnit(
        @Nullable
        final java.lang.String upToUnit) {
        rememberChangedField("upToUnit", this.upToUnit);
        this.upToUnit = upToUnit;
    }

}
