
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.namespaces.maintenancelookuptabledata;

import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>MaintainRowResult</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class MaintainRowResult
    extends VdmComplex<MaintainRowResult>
{

    @Getter
    private final java.lang.String odataType = "MaintenanceLookupTableDataService.MaintainRowResult";
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @return
     *     The iD contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("ID")
    private UUID iD;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<MaintainRowResult> ID = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<MaintainRowResult>(MaintainRowResult.class, "ID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>result</b></p>
     * 
     * @return
     *     The result contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("result")
    private java.lang.String result;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainRowResult> RESULT = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainRowResult>(MaintainRowResult.class, "result");

    @Nonnull
    @Override
    public Class<MaintainRowResult> getType() {
        return MaintainRowResult.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("ID", getID());
        values.put("result", getResult());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ID")) {
                final Object value = values.remove("ID");
                if ((value == null)||(!value.equals(getID()))) {
                    setID(((UUID) value));
                }
            }
            if (values.containsKey("result")) {
                final Object value = values.remove("result");
                if ((value == null)||(!value.equals(getResult()))) {
                    setResult(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @param iD
     *     The iD to set.
     */
    public void setID(
        @Nullable
        final UUID iD) {
        rememberChangedField("ID", this.iD);
        this.iD = iD;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>result</b></p>
     * 
     * @param result
     *     The result to set.
     */
    public void setResult(
        @Nullable
        final java.lang.String result) {
        rememberChangedField("result", this.result);
        this.result = result;
    }

}
