spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/sd
    username: yousef
    password: 9685
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  main:
    allow-bean-definition-overriding: true

logging.level:
  com.sap.cloud.security.samples.resecurity: DEBUG
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE











# spring:
#   datasource:
#     url: jdbc:localhost:63306/KvPFlzlFMIvr
#     username: 1d568939107c
#     password: ca8bbf2fa529e8443ade6b666c513
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
#   h2:
#     console:
#       enabled: true
#       datasource:
#         url: jdbc:h2:mem:testdb
#   main:
#     allow-bean-definition-overriding: true
#   flyway:
#      url: jdbc:localhost:63306/KvPFlzlFMIvr
#      user: 1d568939107c
#      password: ca8bbf2fa529e8443ade6b666c513


# spring:
#   datasource:
#     url: jdbc:postgresql://postgres-844a8763-6c4b-44ac-9807-3ef3e40c11e8.cqryblsdrbcs.us-east-1.rds.amazonaws.com:5630/KvPFlzlFMIvr
#     username: 1d568939107c
#     password: ca8bbf2fa529e8443ade6b666c513
#     driver-class-name: org.postgresql.Driver


