spring:
  datasource:
    url: jdbc:mysql://mysql.sd.svc.cluster.local:3306/mysql
    username: admin
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true


#spring:
#  datasource:
#    url: jdbc:postgresql://postgres.trial.svc.cluster.local:5432/postgres
#    username: postgres
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties.hibernate:
#      .hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect