#spring:
#  flyway:
#    locations: classpath:/db/migration
#    schemas: postgres
#    baselineOnMigrate: true
#    enabled: true
#  datasource:
#    driverClassName: org.postgresql.Driver
#    #    url: jdbc:postgresql://localhost:5432/postgres
#    #    username: postgres
#    #    password: postgres
#    url: ${vcap.services.postgresql-db.credentials.uri}
#    username: ${vcap.services.postgresql-db.credentials.username}
#    password: ${vcap.services.postgresql-db.credentials.password}
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 8080
#
#logging:
#  level:
#    root: info

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  com.sap.cloud.security.samples.resecurity: DEBUG
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

sap.security.services:
  identity:
    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
    domains:
      - localhost                 # SecurityTest.DEFAULT_DOMAIN
  xsuaa:
    xsappname: xsapp!t0815        # SecurityTest.DEFAULT_APP_ID
    uaadomain: localhost          # SecurityTest.DEFAULT_DOMAIN
    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
    url:       http://localhost   # SecurityTest.DEFAULT_URL

#spring:
#  datasource:
#    url: jdbc:mysql://mysql.sd.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true



#spring:
#  datasource:
#    url: jdbc:mysql://192.168.199.132:3306/mysql?useSSL=false&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true
#
#
#    defer-datasource-initialization: true
#    url: jdbc:mysql://mysql.security.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword