#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#scim:
#  api:
#    url: https://aji26ufcs.trial-accounts.ondemand.com/service/scim/Users
#    username: facbddf3-d119-4f36-bb81-0dc8a644a8cb
#    password: nY17h3A5/YsCGx0K3LsDGhzqp]FBJYZ?7o/
#

logging.level:
  com.sap.cloud.security.samples.resecurity: DEBUG
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

sap:
  security:
    services:
      xsuaa:
        xsappname: spring-security-hybrid-usage       # SecurityTest.DEFAULT_APP_ID
        uaadomain: localhost          # SecurityTest.DEFAULT_DOMAIN
        clientid: sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
        url: https://aji26ufcs.trial-accounts.ondemand.com   # SecurityTest.DEFAULT_URL




#spring:
#  datasource:
#    url: jdbc:mysql://mysql.sd.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true


#spring:
#  datasource:
#    url: jdbc:mysql://192.168.199.132:3306/mysql?useSSL=false&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true
#
#
#    defer-datasource-initialization: true
#    url: jdbc:mysql://mysql.security.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword



#Local Db Config
#spring:
#  sql:
#    init:
#      mode: always
#  datasource:
#    url: jdbc:postgresql://localhost:63306/RXlSmSjdhOYj
#    username: 4afe5428142c
#    password: b840edce62a20edac29b775
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  main:
#    allow-bean-definition-overriding: true
#


spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-bean-definition-overriding: true
