#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#
#
#  main:
#    allow-circular-references: true


#  mvc:
#    format:
#      date: dd/MM/yyyy

spring:
  datasource:
    url: jdbc:postgresql://172.17.0.8:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties.hibernate:
      .hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true