#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true



logging.level:
  com.sap.cloud.security.samples.resecurity: DEBUG
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#sap.security.services:
#  identity:
#    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
#    domains:
#      - localhost                 # SecurityTest.DEFAULT_DOMAIN
#  xsuaa:
#    xsappname: xsapp!t0815        # SecurityTest.DEFAULT_APP_ID
#    uaadomain: localhost          # SecurityTest.DEFAULT_DOMAIN
#    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
#    url:       http://localhost   # SecurityTest.DEFAULT_URL



#spring:
#  datasource:
#    url: jdbc:mysql://mysql.sd.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true


#spring:
#  datasource:
#    url: jdbc:mysql://192.168.199.132:3306/mysql?useSSL=false&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000
#    username: admin
#    password: P@ssword
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
#    show-sql: true
#
#
#    defer-datasource-initialization: true
#    url: jdbc:mysql://mysql.security.svc.cluster.local:3306/mysql
#    username: admin
#    password: P@ssword



#Local Db Config
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/btpsd
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  cloud:
    xsuaa:
      service-name: "xsuaa-authn"            # replace with your XSUAA service name if applicable
      instance-name: "7e7ca52f-7c13-4ceb-9d3d-89ea49b81979"  # your service instance ID
      client-id: "sb-na-979d7117-f6cf-436f-b1b6-e29a102bd5d1!i2141"  # client ID
      client-secret: "T/kd87uzEDSHzyVTIeXviQY7R1Y="      # client secret
      token:
        uri: "https://authentication.us10.hana.ondemand.com/oauth/token" # token endpoint
      verification-key:
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAx2ZOcKplHEIvBx1j0dNK
        9J/3E8uKrWFnJRBsdrYvSI6gbV2j2vakAobNxGEz0rXVn+Ljz+2XMgFxlv8in7co
        W7wzLNkOZDXkI6m27hxAdFtihDzoVGRGDhLkxMytvNcz/uVwoa+RSviA3kJ56s7D
        5h2kXsVEUQVHURvfku6MwDO0+ZnEuY174QY6NiwCn6DiMDyQWFtPwHT3l2b9uQaL
        h2szCC21Stze788prD142LePX1CdhRLkwrOZOoAlMNrEdlqqNLadO5WX2m71VICI
        Gjp6iQ4qFHPPJ8tD0d7cRSFnjsBXcbGfzFEhDoYTAF37upXQhhsQywP37AD2q0E9
        LqRwaMkYOuDEEY5Q/Ph9EVeu8zmWbNRQCoqwJ4CbTJ2CMgYCGPj2cgc+lKkPXQOI
        AYN8yh2MaLDPybV0P+dBMI9z2jeeT5ODRsgyfa+7ucLQnOXrR8fRUgULbmtLfHNq
        GZOmhD1cN0MI+S6KxqvPDJmqHOn+nGAQ7uXnW9mjXlNwn3xqZgoXP7+sMRoldDuw
        GcCIAjRF7DOvNkT0cgyYIJD98tCHMWVm/Q6AxKsEwnvxp55g+wNaVaG20qRyDssR
        2DTCQW4cpkgZpWk6jKHZh6tsgzcm0EOB2h0LQiN/hM9sF/BX2cd8ihXfxgWuEkbL
        XWjQAXI68eIOaUJ1LqsoEJsCAwEAAQ==
      xsappname: "na-979d7117-f6cf-436f-b1b6-e29a102bd5d1!i2141" # your xsappname
      uaadomain: "authentication.us10.hana.ondemand.com"  # UAA domain
      credential-type: "instance-secret"   # credential type





