
package com.example.datamodel.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CO_FNDEI_UNITOFMEASUREMENT_RL_service", targetNamespace = "http://sap.com/xi/FNDEI", wsdlLocation = "file:/home/hagar/BTP-SD/src/main/resources/wsdl/CO_FNDEI_UNITOFMEASUREMENT_RL.wsdl")
public class COFNDEIUNITOFMEASUREMENTRLService
    extends Service
{

    private final static URL COFNDEIUNITOFMEASUREMENTRLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COFNDEIUNITOFMEASUREMENTRLSERVICE_EXCEPTION;
    private final static QName COFNDEIUNITOFMEASUREMENTRLSERVICE_QNAME = new QName("http://sap.com/xi/FNDEI", "CO_FNDEI_UNITOFMEASUREMENT_RL_service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/hagar/BTP-SD/src/main/resources/wsdl/CO_FNDEI_UNITOFMEASUREMENT_RL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COFNDEIUNITOFMEASUREMENTRLSERVICE_WSDL_LOCATION = url;
        COFNDEIUNITOFMEASUREMENTRLSERVICE_EXCEPTION = e;
    }

    public COFNDEIUNITOFMEASUREMENTRLService() {
        super(__getWsdlLocation(), COFNDEIUNITOFMEASUREMENTRLSERVICE_QNAME);
    }

    public COFNDEIUNITOFMEASUREMENTRLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COFNDEIUNITOFMEASUREMENTRLSERVICE_QNAME, features);
    }

    public COFNDEIUNITOFMEASUREMENTRLService(URL wsdlLocation) {
        super(wsdlLocation, COFNDEIUNITOFMEASUREMENTRLSERVICE_QNAME);
    }

    public COFNDEIUNITOFMEASUREMENTRLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COFNDEIUNITOFMEASUREMENTRLSERVICE_QNAME, features);
    }

    public COFNDEIUNITOFMEASUREMENTRLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public COFNDEIUNITOFMEASUREMENTRLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnitOfMeasurementMasterDataReplicationBundleRequestOut
     */
    @WebEndpoint(name = "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap11")
    public UnitOfMeasurementMasterDataReplicationBundleRequestOut getCOFNDEIUNITOFMEASUREMENTRLPortSoap11() {
        return super.getPort(new QName("http://sap.com/xi/FNDEI", "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap11"), UnitOfMeasurementMasterDataReplicationBundleRequestOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnitOfMeasurementMasterDataReplicationBundleRequestOut
     */
    @WebEndpoint(name = "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap11")
    public UnitOfMeasurementMasterDataReplicationBundleRequestOut getCOFNDEIUNITOFMEASUREMENTRLPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://sap.com/xi/FNDEI", "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap11"), UnitOfMeasurementMasterDataReplicationBundleRequestOut.class, features);
    }

    /**
     * 
     * @return
     *     returns UnitOfMeasurementMasterDataReplicationBundleRequestOut
     */
    @WebEndpoint(name = "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap12")
    public UnitOfMeasurementMasterDataReplicationBundleRequestOut getCOFNDEIUNITOFMEASUREMENTRLPortSoap12() {
        return super.getPort(new QName("http://sap.com/xi/FNDEI", "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap12"), UnitOfMeasurementMasterDataReplicationBundleRequestOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnitOfMeasurementMasterDataReplicationBundleRequestOut
     */
    @WebEndpoint(name = "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap12")
    public UnitOfMeasurementMasterDataReplicationBundleRequestOut getCOFNDEIUNITOFMEASUREMENTRLPortSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://sap.com/xi/FNDEI", "CO_FNDEI_UNITOFMEASUREMENT_RL_port_soap12"), UnitOfMeasurementMasterDataReplicationBundleRequestOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COFNDEIUNITOFMEASUREMENTRLSERVICE_EXCEPTION!= null) {
            throw COFNDEIUNITOFMEASUREMENTRLSERVICE_EXCEPTION;
        }
        return COFNDEIUNITOFMEASUREMENTRLSERVICE_WSDL_LOCATION;
    }

}
