//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.11 at 01:45:22 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sap.com/xi/FNDEI")
package com.example.datamodel.wsdl;
