
package com.example.datamodel.wsdl;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UnitOfMeasurementMasterDataReplicationBundleRequest_Out", targetNamespace = "http://sap.com/xi/FNDEI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnitOfMeasurementMasterDataReplicationBundleRequestOut {


    /**
     * 
     * @param unitOfMeasurementMasterDataReplicationBundleRequest
     */
    @WebMethod(operationName = "UnitOfMeasurementMasterDataReplicationBundleRequest_Out")
    @Oneway
    public void unitOfMeasurementMasterDataReplicationBundleRequestOut(
        @WebParam(name = "UnitOfMeasurementMasterDataReplicationBundleRequest", targetNamespace = "http://sap.com/xi/FNDEI", partName = "UnitOfMeasurementMasterDataReplicationBundleRequest")
        UnitOfMeasurementMasterDataReplicationBundleRequestMessage unitOfMeasurementMasterDataReplicationBundleRequest);

}
