
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.services;

import java.util.Collection;
import javax.annotation.Nonnull;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.MaintainLookupTableRow;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.MaintainRowResult;
import com.example.datamodel.odata.namespaces.maintenancelookuptabledata.PriceConditionRanges;
import com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CollectionValueActionRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>MaintenanceLookupTableDataService</td></tr></table>
 * 
 */
public interface MaintenanceLookupTableDataService {

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "odata/v4/MaintenanceLookupTableDataService";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    MaintenanceLookupTableDataService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Creates a batch request builder object.
     * 
     * @return
     *     A request builder to handle batch operation on this service. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder#execute(Destination) execute} method on the request builder object.
     */
    @Nonnull
    BatchRequestBuilder batch();

    /**
     * Fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<LookupTables> getAllLookupTables();

    /**
     * Fetch the number of entries from the {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<LookupTables> countLookupTables();

    /**
     * Fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entity using key fields.
     * 
     * @param code
     *     <p>Constraints: Not nullable, Maximum length: 20</p>
     * @return
     *     A request builder to fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables LookupTables} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTables>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<LookupTables> getLookupTablesByKey(final String code);

    /**
     * Fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<LookupTableInputs> getAllLookupTableInputs();

    /**
     * Fetch the number of entries from the {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<LookupTableInputs> countLookupTableInputs();

    /**
     * Fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entity using key fields.
     * 
     * @param code
     *     <p>Constraints: Not nullable, Maximum length: 20</p>
     * @return
     *     A request builder to fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs LookupTableInputs} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableInputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<LookupTableInputs> getLookupTableInputsByKey(final String code);

    /**
     * Fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<LookupTableOutputs> getAllLookupTableOutputs();

    /**
     * Fetch the number of entries from the {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<LookupTableOutputs> countLookupTableOutputs();

    /**
     * Fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entity using key fields.
     * 
     * @param code
     *     <p>Constraints: Not nullable, Maximum length: 20</p>
     * @return
     *     A request builder to fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs LookupTableOutputs} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableOutputs>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<LookupTableOutputs> getLookupTableOutputsByKey(final String code);

    /**
     * Fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.PriceConditionRanges PriceConditionRanges} entity using key fields.
     * 
     * @return
     *     A request builder to fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.PriceConditionRanges PriceConditionRanges} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.PriceConditionRanges>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<PriceConditionRanges> getPriceConditionRangesByKey();

    /**
     * Fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<LookupTableRowsParameters> getAllLookupTableRows();

    /**
     * Fetch the number of entries from the {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<LookupTableRowsParameters> countLookupTableRows();

    /**
     * Fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity using key fields.
     * 
     * @param lookupTableCode
     *     <p>Constraints: Not nullable, Maximum length: 20</p>
     * @return
     *     A request builder to fetch a single {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<LookupTableRowsParameters> getLookupTableRowsByKey(final String lookupTableCode);

    /**
     * Create a new {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity and save it to the S/4HANA system.
     * 
     * @param lookupTableRowsParameters
     *     {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity object that will be created in the S/4HANA system.
     * @return
     *     A request builder to create a new {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CreateRequestBuilder<LookupTableRowsParameters> createLookupTableRows(
        @Nonnull
        final LookupTableRowsParameters lookupTableRowsParameters);

    /**
     * Update an existing {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity and save it to the S/4HANA system.
     * 
     * @param lookupTableRowsParameters
     *     {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<LookupTableRowsParameters> updateLookupTableRows(
        @Nonnull
        final LookupTableRowsParameters lookupTableRowsParameters);

    /**
     * Deletes an existing {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity in the S/4HANA system.
     * 
     * @param lookupTableRowsParameters
     *     {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters LookupTableRowsParameters} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<com.example.datamodel.odata.namespaces.maintenancelookuptabledata.LookupTableRowsParameters>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<LookupTableRowsParameters> deleteLookupTableRows(
        @Nonnull
        final LookupTableRowsParameters lookupTableRowsParameters);

    /**
     * <p>Creates a request builder for the <b>maintainRows</b> OData action.</p>
     * 
     * @param rows
     *     Constraints: Not nullable<p>Original parameter name from the Odata EDM: <b>rows</b></p>
     * @return
     *     A request builder object that will execute the <b>maintainRows</b> OData action with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CollectionValueActionRequestBuilder#execute execute} method on the request builder object.
     */
    @Nonnull
    CollectionValueActionRequestBuilder<MaintainRowResult> maintainRows(
        @Nonnull
        final Collection<MaintainLookupTableRow> rows);

}
