
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.namespaces.maintenancelookuptabledata;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.DecimalDescriptor;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>MaintainLookupTableRow</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class MaintainLookupTableRow
    extends VdmComplex<MaintainLookupTableRow>
{

    @Getter
    private final java.lang.String odataType = "MaintenanceLookupTableDataService.MaintainLookupTableRow";
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @return
     *     The iD contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("ID")
    private UUID iD;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<MaintainLookupTableRow> ID = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<MaintainLookupTableRow>(MaintainLookupTableRow.class, "ID");
    /**
     * Constraints: Nullable, Maximum length: 32 <p>Original property name from the Odata EDM: <b>rowTag</b></p>
     * 
     * @return
     *     The rowTag contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("rowTag")
    private java.lang.String rowTag;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> ROW_TAG = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "rowTag");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString0</b></p>
     * 
     * @return
     *     The inputString0 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString0")
    private java.lang.String inputString0;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING0 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString0");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString1</b></p>
     * 
     * @return
     *     The inputString1 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString1")
    private java.lang.String inputString1;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING1 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString1");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString2</b></p>
     * 
     * @return
     *     The inputString2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString2")
    private java.lang.String inputString2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString2");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString3</b></p>
     * 
     * @return
     *     The inputString3 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString3")
    private java.lang.String inputString3;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING3 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString3");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString4</b></p>
     * 
     * @return
     *     The inputString4 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString4")
    private java.lang.String inputString4;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING4 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString4");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString5</b></p>
     * 
     * @return
     *     The inputString5 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString5")
    private java.lang.String inputString5;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING5 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString5");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString6</b></p>
     * 
     * @return
     *     The inputString6 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString6")
    private java.lang.String inputString6;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING6 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString6");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString7</b></p>
     * 
     * @return
     *     The inputString7 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString7")
    private java.lang.String inputString7;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING7 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString7");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString8</b></p>
     * 
     * @return
     *     The inputString8 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString8")
    private java.lang.String inputString8;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING8 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString8");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString9</b></p>
     * 
     * @return
     *     The inputString9 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString9")
    private java.lang.String inputString9;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING9 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString9");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString10</b></p>
     * 
     * @return
     *     The inputString10 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString10")
    private java.lang.String inputString10;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING10 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString10");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString11</b></p>
     * 
     * @return
     *     The inputString11 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString11")
    private java.lang.String inputString11;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING11 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString11");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString12</b></p>
     * 
     * @return
     *     The inputString12 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString12")
    private java.lang.String inputString12;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING12 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString12");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString13</b></p>
     * 
     * @return
     *     The inputString13 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString13")
    private java.lang.String inputString13;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING13 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString13");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString14</b></p>
     * 
     * @return
     *     The inputString14 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("inputString14")
    private java.lang.String inputString14;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> INPUT_STRING14 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "inputString14");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>validityStart</b></p>
     * 
     * @return
     *     The validityStart contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("validityStart")
    private LocalDate validityStart;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Date<MaintainLookupTableRow> VALIDITY_START = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Date<MaintainLookupTableRow>(MaintainLookupTableRow.class, "validityStart");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>validityEnd</b></p>
     * 
     * @return
     *     The validityEnd contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("validityEnd")
    private LocalDate validityEnd;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Date<MaintainLookupTableRow> VALIDITY_END = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Date<MaintainLookupTableRow>(MaintainLookupTableRow.class, "validityEnd");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString0</b></p>
     * 
     * @return
     *     The outputString0 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString0")
    private java.lang.String outputString0;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING0 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString0");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString1</b></p>
     * 
     * @return
     *     The outputString1 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString1")
    private java.lang.String outputString1;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING1 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString1");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString2</b></p>
     * 
     * @return
     *     The outputString2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString2")
    private java.lang.String outputString2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString2");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString3</b></p>
     * 
     * @return
     *     The outputString3 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString3")
    private java.lang.String outputString3;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING3 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString3");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString4</b></p>
     * 
     * @return
     *     The outputString4 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString4")
    private java.lang.String outputString4;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING4 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString4");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString5</b></p>
     * 
     * @return
     *     The outputString5 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString5")
    private java.lang.String outputString5;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING5 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString5");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString6</b></p>
     * 
     * @return
     *     The outputString6 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString6")
    private java.lang.String outputString6;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING6 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString6");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString7</b></p>
     * 
     * @return
     *     The outputString7 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString7")
    private java.lang.String outputString7;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING7 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString7");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString8</b></p>
     * 
     * @return
     *     The outputString8 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString8")
    private java.lang.String outputString8;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING8 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString8");
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString9</b></p>
     * 
     * @return
     *     The outputString9 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputString9")
    private java.lang.String outputString9;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_STRING9 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputString9");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue0</b></p>
     * 
     * @return
     *     The outputQuantityValue0 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue0")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue0;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE0 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue0");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit0</b></p>
     * 
     * @return
     *     The outputQuantityUnit0 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit0")
    private java.lang.String outputQuantityUnit0;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT0 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit0");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue1</b></p>
     * 
     * @return
     *     The outputQuantityValue1 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue1")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue1;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE1 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue1");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit1</b></p>
     * 
     * @return
     *     The outputQuantityUnit1 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit1")
    private java.lang.String outputQuantityUnit1;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT1 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit1");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue2</b></p>
     * 
     * @return
     *     The outputQuantityValue2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue2")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue2");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit2</b></p>
     * 
     * @return
     *     The outputQuantityUnit2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit2")
    private java.lang.String outputQuantityUnit2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit2");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue3</b></p>
     * 
     * @return
     *     The outputQuantityValue3 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue3")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue3;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE3 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue3");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit3</b></p>
     * 
     * @return
     *     The outputQuantityUnit3 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit3")
    private java.lang.String outputQuantityUnit3;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT3 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit3");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue4</b></p>
     * 
     * @return
     *     The outputQuantityValue4 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue4")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue4;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE4 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue4");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit4</b></p>
     * 
     * @return
     *     The outputQuantityUnit4 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit4")
    private java.lang.String outputQuantityUnit4;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT4 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit4");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue5</b></p>
     * 
     * @return
     *     The outputQuantityValue5 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue5")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue5;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE5 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue5");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit5</b></p>
     * 
     * @return
     *     The outputQuantityUnit5 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit5")
    private java.lang.String outputQuantityUnit5;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT5 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit5");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue6</b></p>
     * 
     * @return
     *     The outputQuantityValue6 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue6")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue6;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE6 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue6");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit6</b></p>
     * 
     * @return
     *     The outputQuantityUnit6 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit6")
    private java.lang.String outputQuantityUnit6;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT6 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit6");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue7</b></p>
     * 
     * @return
     *     The outputQuantityValue7 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue7")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue7;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE7 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue7");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit7</b></p>
     * 
     * @return
     *     The outputQuantityUnit7 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit7")
    private java.lang.String outputQuantityUnit7;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT7 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit7");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue8</b></p>
     * 
     * @return
     *     The outputQuantityValue8 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue8")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue8;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE8 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue8");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit8</b></p>
     * 
     * @return
     *     The outputQuantityUnit8 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit8")
    private java.lang.String outputQuantityUnit8;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT8 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit8");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue9</b></p>
     * 
     * @return
     *     The outputQuantityValue9 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityValue9")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal outputQuantityValue9;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow> OUTPUT_QUANTITY_VALUE9 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericDecimal<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityValue9");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit9</b></p>
     * 
     * @return
     *     The outputQuantityUnit9 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("outputQuantityUnit9")
    private java.lang.String outputQuantityUnit9;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OUTPUT_QUANTITY_UNIT9 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "outputQuantityUnit9");
    /**
     * Constraints: Nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>priceConditionType</b></p>
     * 
     * @return
     *     The priceConditionType contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("priceConditionType")
    private java.lang.String priceConditionType;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> PRICE_CONDITION_TYPE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "priceConditionType");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>priceConditionMonetaryAmountCurrency</b></p>
     * 
     * @return
     *     The priceConditionMonetaryAmountCurrency contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("priceConditionMonetaryAmountCurrency")
    private java.lang.String priceConditionMonetaryAmountCurrency;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> PRICE_CONDITION_MONETARY_AMOUNT_CURRENCY = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "priceConditionMonetaryAmountCurrency");
    /**
     * Constraints: Nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>lookupTable_code</b></p>
     * 
     * @return
     *     The lookupTable_code contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("lookupTable_code")
    private java.lang.String lookupTable_code;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> LOOKUP_TABLE_CODE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "lookupTable_code");
    /**
     * Constraints: Nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>operation</b></p>
     * 
     * @return
     *     The operation contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("operation")
    private java.lang.String operation;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow> OPERATION = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<MaintainLookupTableRow>(MaintainLookupTableRow.class, "operation");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>priceConditionRanges</b></p>
     * 
     * @return
     *     The priceConditionRanges contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("priceConditionRanges")
    private java.util.Collection<com_sap_cloud_pricing_calculation_PriceConditionRange> priceConditionRanges;
    /**
     * Use with available request builders to apply the <b>priceConditionRanges</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<MaintainLookupTableRow, com_sap_cloud_pricing_calculation_PriceConditionRange> PRICE_CONDITION_RANGES = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<MaintainLookupTableRow, com_sap_cloud_pricing_calculation_PriceConditionRange>(MaintainLookupTableRow.class, "priceConditionRanges", com_sap_cloud_pricing_calculation_PriceConditionRange.class);

    @Nonnull
    @Override
    public Class<MaintainLookupTableRow> getType() {
        return MaintainLookupTableRow.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("ID", getID());
        values.put("rowTag", getRowTag());
        values.put("inputString0", getInputString0());
        values.put("inputString1", getInputString1());
        values.put("inputString2", getInputString2());
        values.put("inputString3", getInputString3());
        values.put("inputString4", getInputString4());
        values.put("inputString5", getInputString5());
        values.put("inputString6", getInputString6());
        values.put("inputString7", getInputString7());
        values.put("inputString8", getInputString8());
        values.put("inputString9", getInputString9());
        values.put("inputString10", getInputString10());
        values.put("inputString11", getInputString11());
        values.put("inputString12", getInputString12());
        values.put("inputString13", getInputString13());
        values.put("inputString14", getInputString14());
        values.put("validityStart", getValidityStart());
        values.put("validityEnd", getValidityEnd());
        values.put("outputString0", getOutputString0());
        values.put("outputString1", getOutputString1());
        values.put("outputString2", getOutputString2());
        values.put("outputString3", getOutputString3());
        values.put("outputString4", getOutputString4());
        values.put("outputString5", getOutputString5());
        values.put("outputString6", getOutputString6());
        values.put("outputString7", getOutputString7());
        values.put("outputString8", getOutputString8());
        values.put("outputString9", getOutputString9());
        values.put("outputQuantityValue0", getOutputQuantityValue0());
        values.put("outputQuantityUnit0", getOutputQuantityUnit0());
        values.put("outputQuantityValue1", getOutputQuantityValue1());
        values.put("outputQuantityUnit1", getOutputQuantityUnit1());
        values.put("outputQuantityValue2", getOutputQuantityValue2());
        values.put("outputQuantityUnit2", getOutputQuantityUnit2());
        values.put("outputQuantityValue3", getOutputQuantityValue3());
        values.put("outputQuantityUnit3", getOutputQuantityUnit3());
        values.put("outputQuantityValue4", getOutputQuantityValue4());
        values.put("outputQuantityUnit4", getOutputQuantityUnit4());
        values.put("outputQuantityValue5", getOutputQuantityValue5());
        values.put("outputQuantityUnit5", getOutputQuantityUnit5());
        values.put("outputQuantityValue6", getOutputQuantityValue6());
        values.put("outputQuantityUnit6", getOutputQuantityUnit6());
        values.put("outputQuantityValue7", getOutputQuantityValue7());
        values.put("outputQuantityUnit7", getOutputQuantityUnit7());
        values.put("outputQuantityValue8", getOutputQuantityValue8());
        values.put("outputQuantityUnit8", getOutputQuantityUnit8());
        values.put("outputQuantityValue9", getOutputQuantityValue9());
        values.put("outputQuantityUnit9", getOutputQuantityUnit9());
        values.put("priceConditionType", getPriceConditionType());
        values.put("priceConditionMonetaryAmountCurrency", getPriceConditionMonetaryAmountCurrency());
        values.put("lookupTable_code", getLookupTable_code());
        values.put("operation", getOperation());
        values.put("priceConditionRanges", getPriceConditionRanges());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ID")) {
                final Object value = values.remove("ID");
                if ((value == null)||(!value.equals(getID()))) {
                    setID(((UUID) value));
                }
            }
            if (values.containsKey("rowTag")) {
                final Object value = values.remove("rowTag");
                if ((value == null)||(!value.equals(getRowTag()))) {
                    setRowTag(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString0")) {
                final Object value = values.remove("inputString0");
                if ((value == null)||(!value.equals(getInputString0()))) {
                    setInputString0(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString1")) {
                final Object value = values.remove("inputString1");
                if ((value == null)||(!value.equals(getInputString1()))) {
                    setInputString1(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString2")) {
                final Object value = values.remove("inputString2");
                if ((value == null)||(!value.equals(getInputString2()))) {
                    setInputString2(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString3")) {
                final Object value = values.remove("inputString3");
                if ((value == null)||(!value.equals(getInputString3()))) {
                    setInputString3(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString4")) {
                final Object value = values.remove("inputString4");
                if ((value == null)||(!value.equals(getInputString4()))) {
                    setInputString4(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString5")) {
                final Object value = values.remove("inputString5");
                if ((value == null)||(!value.equals(getInputString5()))) {
                    setInputString5(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString6")) {
                final Object value = values.remove("inputString6");
                if ((value == null)||(!value.equals(getInputString6()))) {
                    setInputString6(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString7")) {
                final Object value = values.remove("inputString7");
                if ((value == null)||(!value.equals(getInputString7()))) {
                    setInputString7(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString8")) {
                final Object value = values.remove("inputString8");
                if ((value == null)||(!value.equals(getInputString8()))) {
                    setInputString8(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString9")) {
                final Object value = values.remove("inputString9");
                if ((value == null)||(!value.equals(getInputString9()))) {
                    setInputString9(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString10")) {
                final Object value = values.remove("inputString10");
                if ((value == null)||(!value.equals(getInputString10()))) {
                    setInputString10(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString11")) {
                final Object value = values.remove("inputString11");
                if ((value == null)||(!value.equals(getInputString11()))) {
                    setInputString11(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString12")) {
                final Object value = values.remove("inputString12");
                if ((value == null)||(!value.equals(getInputString12()))) {
                    setInputString12(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString13")) {
                final Object value = values.remove("inputString13");
                if ((value == null)||(!value.equals(getInputString13()))) {
                    setInputString13(((java.lang.String) value));
                }
            }
            if (values.containsKey("inputString14")) {
                final Object value = values.remove("inputString14");
                if ((value == null)||(!value.equals(getInputString14()))) {
                    setInputString14(((java.lang.String) value));
                }
            }
            if (values.containsKey("validityStart")) {
                final Object value = values.remove("validityStart");
                if ((value == null)||(!value.equals(getValidityStart()))) {
                    setValidityStart(((LocalDate) value));
                }
            }
            if (values.containsKey("validityEnd")) {
                final Object value = values.remove("validityEnd");
                if ((value == null)||(!value.equals(getValidityEnd()))) {
                    setValidityEnd(((LocalDate) value));
                }
            }
            if (values.containsKey("outputString0")) {
                final Object value = values.remove("outputString0");
                if ((value == null)||(!value.equals(getOutputString0()))) {
                    setOutputString0(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString1")) {
                final Object value = values.remove("outputString1");
                if ((value == null)||(!value.equals(getOutputString1()))) {
                    setOutputString1(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString2")) {
                final Object value = values.remove("outputString2");
                if ((value == null)||(!value.equals(getOutputString2()))) {
                    setOutputString2(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString3")) {
                final Object value = values.remove("outputString3");
                if ((value == null)||(!value.equals(getOutputString3()))) {
                    setOutputString3(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString4")) {
                final Object value = values.remove("outputString4");
                if ((value == null)||(!value.equals(getOutputString4()))) {
                    setOutputString4(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString5")) {
                final Object value = values.remove("outputString5");
                if ((value == null)||(!value.equals(getOutputString5()))) {
                    setOutputString5(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString6")) {
                final Object value = values.remove("outputString6");
                if ((value == null)||(!value.equals(getOutputString6()))) {
                    setOutputString6(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString7")) {
                final Object value = values.remove("outputString7");
                if ((value == null)||(!value.equals(getOutputString7()))) {
                    setOutputString7(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString8")) {
                final Object value = values.remove("outputString8");
                if ((value == null)||(!value.equals(getOutputString8()))) {
                    setOutputString8(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputString9")) {
                final Object value = values.remove("outputString9");
                if ((value == null)||(!value.equals(getOutputString9()))) {
                    setOutputString9(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue0")) {
                final Object value = values.remove("outputQuantityValue0");
                if ((value == null)||(!value.equals(getOutputQuantityValue0()))) {
                    setOutputQuantityValue0(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit0")) {
                final Object value = values.remove("outputQuantityUnit0");
                if ((value == null)||(!value.equals(getOutputQuantityUnit0()))) {
                    setOutputQuantityUnit0(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue1")) {
                final Object value = values.remove("outputQuantityValue1");
                if ((value == null)||(!value.equals(getOutputQuantityValue1()))) {
                    setOutputQuantityValue1(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit1")) {
                final Object value = values.remove("outputQuantityUnit1");
                if ((value == null)||(!value.equals(getOutputQuantityUnit1()))) {
                    setOutputQuantityUnit1(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue2")) {
                final Object value = values.remove("outputQuantityValue2");
                if ((value == null)||(!value.equals(getOutputQuantityValue2()))) {
                    setOutputQuantityValue2(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit2")) {
                final Object value = values.remove("outputQuantityUnit2");
                if ((value == null)||(!value.equals(getOutputQuantityUnit2()))) {
                    setOutputQuantityUnit2(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue3")) {
                final Object value = values.remove("outputQuantityValue3");
                if ((value == null)||(!value.equals(getOutputQuantityValue3()))) {
                    setOutputQuantityValue3(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit3")) {
                final Object value = values.remove("outputQuantityUnit3");
                if ((value == null)||(!value.equals(getOutputQuantityUnit3()))) {
                    setOutputQuantityUnit3(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue4")) {
                final Object value = values.remove("outputQuantityValue4");
                if ((value == null)||(!value.equals(getOutputQuantityValue4()))) {
                    setOutputQuantityValue4(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit4")) {
                final Object value = values.remove("outputQuantityUnit4");
                if ((value == null)||(!value.equals(getOutputQuantityUnit4()))) {
                    setOutputQuantityUnit4(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue5")) {
                final Object value = values.remove("outputQuantityValue5");
                if ((value == null)||(!value.equals(getOutputQuantityValue5()))) {
                    setOutputQuantityValue5(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit5")) {
                final Object value = values.remove("outputQuantityUnit5");
                if ((value == null)||(!value.equals(getOutputQuantityUnit5()))) {
                    setOutputQuantityUnit5(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue6")) {
                final Object value = values.remove("outputQuantityValue6");
                if ((value == null)||(!value.equals(getOutputQuantityValue6()))) {
                    setOutputQuantityValue6(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit6")) {
                final Object value = values.remove("outputQuantityUnit6");
                if ((value == null)||(!value.equals(getOutputQuantityUnit6()))) {
                    setOutputQuantityUnit6(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue7")) {
                final Object value = values.remove("outputQuantityValue7");
                if ((value == null)||(!value.equals(getOutputQuantityValue7()))) {
                    setOutputQuantityValue7(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit7")) {
                final Object value = values.remove("outputQuantityUnit7");
                if ((value == null)||(!value.equals(getOutputQuantityUnit7()))) {
                    setOutputQuantityUnit7(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue8")) {
                final Object value = values.remove("outputQuantityValue8");
                if ((value == null)||(!value.equals(getOutputQuantityValue8()))) {
                    setOutputQuantityValue8(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit8")) {
                final Object value = values.remove("outputQuantityUnit8");
                if ((value == null)||(!value.equals(getOutputQuantityUnit8()))) {
                    setOutputQuantityUnit8(((java.lang.String) value));
                }
            }
            if (values.containsKey("outputQuantityValue9")) {
                final Object value = values.remove("outputQuantityValue9");
                if ((value == null)||(!value.equals(getOutputQuantityValue9()))) {
                    setOutputQuantityValue9(((BigDecimal) value));
                }
            }
            if (values.containsKey("outputQuantityUnit9")) {
                final Object value = values.remove("outputQuantityUnit9");
                if ((value == null)||(!value.equals(getOutputQuantityUnit9()))) {
                    setOutputQuantityUnit9(((java.lang.String) value));
                }
            }
            if (values.containsKey("priceConditionType")) {
                final Object value = values.remove("priceConditionType");
                if ((value == null)||(!value.equals(getPriceConditionType()))) {
                    setPriceConditionType(((java.lang.String) value));
                }
            }
            if (values.containsKey("priceConditionMonetaryAmountCurrency")) {
                final Object value = values.remove("priceConditionMonetaryAmountCurrency");
                if ((value == null)||(!value.equals(getPriceConditionMonetaryAmountCurrency()))) {
                    setPriceConditionMonetaryAmountCurrency(((java.lang.String) value));
                }
            }
            if (values.containsKey("lookupTable_code")) {
                final Object value = values.remove("lookupTable_code");
                if ((value == null)||(!value.equals(getLookupTable_code()))) {
                    setLookupTable_code(((java.lang.String) value));
                }
            }
            if (values.containsKey("operation")) {
                final Object value = values.remove("operation");
                if ((value == null)||(!value.equals(getOperation()))) {
                    setOperation(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
            if (values.containsKey("priceConditionRanges")) {
                final Object value = values.remove("priceConditionRanges");
                if (value instanceof Iterable) {
                    final LinkedList<com_sap_cloud_pricing_calculation_PriceConditionRange> priceConditionRanges = new LinkedList<com_sap_cloud_pricing_calculation_PriceConditionRange>();
                    for (Object properties: ((Iterable<?> ) value)) {
                        if (properties instanceof Map) {
                            final com_sap_cloud_pricing_calculation_PriceConditionRange item = new com_sap_cloud_pricing_calculation_PriceConditionRange();
                            @SuppressWarnings("unchecked")
                            final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                            item.fromMap(inputMap);
                            priceConditionRanges.add(item);
                        }
                    }
                    setPriceConditionRanges(priceConditionRanges);
                }
                if ((value == null)&&(getPriceConditionRanges()!= null)) {
                    setPriceConditionRanges(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @param iD
     *     The iD to set.
     */
    public void setID(
        @Nullable
        final UUID iD) {
        rememberChangedField("ID", this.iD);
        this.iD = iD;
    }

    /**
     * Constraints: Nullable, Maximum length: 32 <p>Original property name from the Odata EDM: <b>rowTag</b></p>
     * 
     * @param rowTag
     *     The rowTag to set.
     */
    public void setRowTag(
        @Nullable
        final java.lang.String rowTag) {
        rememberChangedField("rowTag", this.rowTag);
        this.rowTag = rowTag;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString0</b></p>
     * 
     * @param inputString0
     *     The inputString0 to set.
     */
    public void setInputString0(
        @Nullable
        final java.lang.String inputString0) {
        rememberChangedField("inputString0", this.inputString0);
        this.inputString0 = inputString0;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString1</b></p>
     * 
     * @param inputString1
     *     The inputString1 to set.
     */
    public void setInputString1(
        @Nullable
        final java.lang.String inputString1) {
        rememberChangedField("inputString1", this.inputString1);
        this.inputString1 = inputString1;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString2</b></p>
     * 
     * @param inputString2
     *     The inputString2 to set.
     */
    public void setInputString2(
        @Nullable
        final java.lang.String inputString2) {
        rememberChangedField("inputString2", this.inputString2);
        this.inputString2 = inputString2;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString3</b></p>
     * 
     * @param inputString3
     *     The inputString3 to set.
     */
    public void setInputString3(
        @Nullable
        final java.lang.String inputString3) {
        rememberChangedField("inputString3", this.inputString3);
        this.inputString3 = inputString3;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString4</b></p>
     * 
     * @param inputString4
     *     The inputString4 to set.
     */
    public void setInputString4(
        @Nullable
        final java.lang.String inputString4) {
        rememberChangedField("inputString4", this.inputString4);
        this.inputString4 = inputString4;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString5</b></p>
     * 
     * @param inputString5
     *     The inputString5 to set.
     */
    public void setInputString5(
        @Nullable
        final java.lang.String inputString5) {
        rememberChangedField("inputString5", this.inputString5);
        this.inputString5 = inputString5;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString6</b></p>
     * 
     * @param inputString6
     *     The inputString6 to set.
     */
    public void setInputString6(
        @Nullable
        final java.lang.String inputString6) {
        rememberChangedField("inputString6", this.inputString6);
        this.inputString6 = inputString6;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString7</b></p>
     * 
     * @param inputString7
     *     The inputString7 to set.
     */
    public void setInputString7(
        @Nullable
        final java.lang.String inputString7) {
        rememberChangedField("inputString7", this.inputString7);
        this.inputString7 = inputString7;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString8</b></p>
     * 
     * @param inputString8
     *     The inputString8 to set.
     */
    public void setInputString8(
        @Nullable
        final java.lang.String inputString8) {
        rememberChangedField("inputString8", this.inputString8);
        this.inputString8 = inputString8;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString9</b></p>
     * 
     * @param inputString9
     *     The inputString9 to set.
     */
    public void setInputString9(
        @Nullable
        final java.lang.String inputString9) {
        rememberChangedField("inputString9", this.inputString9);
        this.inputString9 = inputString9;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString10</b></p>
     * 
     * @param inputString10
     *     The inputString10 to set.
     */
    public void setInputString10(
        @Nullable
        final java.lang.String inputString10) {
        rememberChangedField("inputString10", this.inputString10);
        this.inputString10 = inputString10;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString11</b></p>
     * 
     * @param inputString11
     *     The inputString11 to set.
     */
    public void setInputString11(
        @Nullable
        final java.lang.String inputString11) {
        rememberChangedField("inputString11", this.inputString11);
        this.inputString11 = inputString11;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString12</b></p>
     * 
     * @param inputString12
     *     The inputString12 to set.
     */
    public void setInputString12(
        @Nullable
        final java.lang.String inputString12) {
        rememberChangedField("inputString12", this.inputString12);
        this.inputString12 = inputString12;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString13</b></p>
     * 
     * @param inputString13
     *     The inputString13 to set.
     */
    public void setInputString13(
        @Nullable
        final java.lang.String inputString13) {
        rememberChangedField("inputString13", this.inputString13);
        this.inputString13 = inputString13;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>inputString14</b></p>
     * 
     * @param inputString14
     *     The inputString14 to set.
     */
    public void setInputString14(
        @Nullable
        final java.lang.String inputString14) {
        rememberChangedField("inputString14", this.inputString14);
        this.inputString14 = inputString14;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>validityStart</b></p>
     * 
     * @param validityStart
     *     The validityStart to set.
     */
    public void setValidityStart(
        @Nullable
        final LocalDate validityStart) {
        rememberChangedField("validityStart", this.validityStart);
        this.validityStart = validityStart;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>validityEnd</b></p>
     * 
     * @param validityEnd
     *     The validityEnd to set.
     */
    public void setValidityEnd(
        @Nullable
        final LocalDate validityEnd) {
        rememberChangedField("validityEnd", this.validityEnd);
        this.validityEnd = validityEnd;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString0</b></p>
     * 
     * @param outputString0
     *     The outputString0 to set.
     */
    public void setOutputString0(
        @Nullable
        final java.lang.String outputString0) {
        rememberChangedField("outputString0", this.outputString0);
        this.outputString0 = outputString0;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString1</b></p>
     * 
     * @param outputString1
     *     The outputString1 to set.
     */
    public void setOutputString1(
        @Nullable
        final java.lang.String outputString1) {
        rememberChangedField("outputString1", this.outputString1);
        this.outputString1 = outputString1;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString2</b></p>
     * 
     * @param outputString2
     *     The outputString2 to set.
     */
    public void setOutputString2(
        @Nullable
        final java.lang.String outputString2) {
        rememberChangedField("outputString2", this.outputString2);
        this.outputString2 = outputString2;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString3</b></p>
     * 
     * @param outputString3
     *     The outputString3 to set.
     */
    public void setOutputString3(
        @Nullable
        final java.lang.String outputString3) {
        rememberChangedField("outputString3", this.outputString3);
        this.outputString3 = outputString3;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString4</b></p>
     * 
     * @param outputString4
     *     The outputString4 to set.
     */
    public void setOutputString4(
        @Nullable
        final java.lang.String outputString4) {
        rememberChangedField("outputString4", this.outputString4);
        this.outputString4 = outputString4;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString5</b></p>
     * 
     * @param outputString5
     *     The outputString5 to set.
     */
    public void setOutputString5(
        @Nullable
        final java.lang.String outputString5) {
        rememberChangedField("outputString5", this.outputString5);
        this.outputString5 = outputString5;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString6</b></p>
     * 
     * @param outputString6
     *     The outputString6 to set.
     */
    public void setOutputString6(
        @Nullable
        final java.lang.String outputString6) {
        rememberChangedField("outputString6", this.outputString6);
        this.outputString6 = outputString6;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString7</b></p>
     * 
     * @param outputString7
     *     The outputString7 to set.
     */
    public void setOutputString7(
        @Nullable
        final java.lang.String outputString7) {
        rememberChangedField("outputString7", this.outputString7);
        this.outputString7 = outputString7;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString8</b></p>
     * 
     * @param outputString8
     *     The outputString8 to set.
     */
    public void setOutputString8(
        @Nullable
        final java.lang.String outputString8) {
        rememberChangedField("outputString8", this.outputString8);
        this.outputString8 = outputString8;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>outputString9</b></p>
     * 
     * @param outputString9
     *     The outputString9 to set.
     */
    public void setOutputString9(
        @Nullable
        final java.lang.String outputString9) {
        rememberChangedField("outputString9", this.outputString9);
        this.outputString9 = outputString9;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue0</b></p>
     * 
     * @param outputQuantityValue0
     *     The outputQuantityValue0 to set.
     */
    public void setOutputQuantityValue0(
        @Nullable
        final BigDecimal outputQuantityValue0) {
        rememberChangedField("outputQuantityValue0", this.outputQuantityValue0);
        this.outputQuantityValue0 = outputQuantityValue0;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit0</b></p>
     * 
     * @param outputQuantityUnit0
     *     The outputQuantityUnit0 to set.
     */
    public void setOutputQuantityUnit0(
        @Nullable
        final java.lang.String outputQuantityUnit0) {
        rememberChangedField("outputQuantityUnit0", this.outputQuantityUnit0);
        this.outputQuantityUnit0 = outputQuantityUnit0;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue1</b></p>
     * 
     * @param outputQuantityValue1
     *     The outputQuantityValue1 to set.
     */
    public void setOutputQuantityValue1(
        @Nullable
        final BigDecimal outputQuantityValue1) {
        rememberChangedField("outputQuantityValue1", this.outputQuantityValue1);
        this.outputQuantityValue1 = outputQuantityValue1;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit1</b></p>
     * 
     * @param outputQuantityUnit1
     *     The outputQuantityUnit1 to set.
     */
    public void setOutputQuantityUnit1(
        @Nullable
        final java.lang.String outputQuantityUnit1) {
        rememberChangedField("outputQuantityUnit1", this.outputQuantityUnit1);
        this.outputQuantityUnit1 = outputQuantityUnit1;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue2</b></p>
     * 
     * @param outputQuantityValue2
     *     The outputQuantityValue2 to set.
     */
    public void setOutputQuantityValue2(
        @Nullable
        final BigDecimal outputQuantityValue2) {
        rememberChangedField("outputQuantityValue2", this.outputQuantityValue2);
        this.outputQuantityValue2 = outputQuantityValue2;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit2</b></p>
     * 
     * @param outputQuantityUnit2
     *     The outputQuantityUnit2 to set.
     */
    public void setOutputQuantityUnit2(
        @Nullable
        final java.lang.String outputQuantityUnit2) {
        rememberChangedField("outputQuantityUnit2", this.outputQuantityUnit2);
        this.outputQuantityUnit2 = outputQuantityUnit2;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue3</b></p>
     * 
     * @param outputQuantityValue3
     *     The outputQuantityValue3 to set.
     */
    public void setOutputQuantityValue3(
        @Nullable
        final BigDecimal outputQuantityValue3) {
        rememberChangedField("outputQuantityValue3", this.outputQuantityValue3);
        this.outputQuantityValue3 = outputQuantityValue3;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit3</b></p>
     * 
     * @param outputQuantityUnit3
     *     The outputQuantityUnit3 to set.
     */
    public void setOutputQuantityUnit3(
        @Nullable
        final java.lang.String outputQuantityUnit3) {
        rememberChangedField("outputQuantityUnit3", this.outputQuantityUnit3);
        this.outputQuantityUnit3 = outputQuantityUnit3;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue4</b></p>
     * 
     * @param outputQuantityValue4
     *     The outputQuantityValue4 to set.
     */
    public void setOutputQuantityValue4(
        @Nullable
        final BigDecimal outputQuantityValue4) {
        rememberChangedField("outputQuantityValue4", this.outputQuantityValue4);
        this.outputQuantityValue4 = outputQuantityValue4;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit4</b></p>
     * 
     * @param outputQuantityUnit4
     *     The outputQuantityUnit4 to set.
     */
    public void setOutputQuantityUnit4(
        @Nullable
        final java.lang.String outputQuantityUnit4) {
        rememberChangedField("outputQuantityUnit4", this.outputQuantityUnit4);
        this.outputQuantityUnit4 = outputQuantityUnit4;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue5</b></p>
     * 
     * @param outputQuantityValue5
     *     The outputQuantityValue5 to set.
     */
    public void setOutputQuantityValue5(
        @Nullable
        final BigDecimal outputQuantityValue5) {
        rememberChangedField("outputQuantityValue5", this.outputQuantityValue5);
        this.outputQuantityValue5 = outputQuantityValue5;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit5</b></p>
     * 
     * @param outputQuantityUnit5
     *     The outputQuantityUnit5 to set.
     */
    public void setOutputQuantityUnit5(
        @Nullable
        final java.lang.String outputQuantityUnit5) {
        rememberChangedField("outputQuantityUnit5", this.outputQuantityUnit5);
        this.outputQuantityUnit5 = outputQuantityUnit5;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue6</b></p>
     * 
     * @param outputQuantityValue6
     *     The outputQuantityValue6 to set.
     */
    public void setOutputQuantityValue6(
        @Nullable
        final BigDecimal outputQuantityValue6) {
        rememberChangedField("outputQuantityValue6", this.outputQuantityValue6);
        this.outputQuantityValue6 = outputQuantityValue6;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit6</b></p>
     * 
     * @param outputQuantityUnit6
     *     The outputQuantityUnit6 to set.
     */
    public void setOutputQuantityUnit6(
        @Nullable
        final java.lang.String outputQuantityUnit6) {
        rememberChangedField("outputQuantityUnit6", this.outputQuantityUnit6);
        this.outputQuantityUnit6 = outputQuantityUnit6;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue7</b></p>
     * 
     * @param outputQuantityValue7
     *     The outputQuantityValue7 to set.
     */
    public void setOutputQuantityValue7(
        @Nullable
        final BigDecimal outputQuantityValue7) {
        rememberChangedField("outputQuantityValue7", this.outputQuantityValue7);
        this.outputQuantityValue7 = outputQuantityValue7;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit7</b></p>
     * 
     * @param outputQuantityUnit7
     *     The outputQuantityUnit7 to set.
     */
    public void setOutputQuantityUnit7(
        @Nullable
        final java.lang.String outputQuantityUnit7) {
        rememberChangedField("outputQuantityUnit7", this.outputQuantityUnit7);
        this.outputQuantityUnit7 = outputQuantityUnit7;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue8</b></p>
     * 
     * @param outputQuantityValue8
     *     The outputQuantityValue8 to set.
     */
    public void setOutputQuantityValue8(
        @Nullable
        final BigDecimal outputQuantityValue8) {
        rememberChangedField("outputQuantityValue8", this.outputQuantityValue8);
        this.outputQuantityValue8 = outputQuantityValue8;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit8</b></p>
     * 
     * @param outputQuantityUnit8
     *     The outputQuantityUnit8 to set.
     */
    public void setOutputQuantityUnit8(
        @Nullable
        final java.lang.String outputQuantityUnit8) {
        rememberChangedField("outputQuantityUnit8", this.outputQuantityUnit8);
        this.outputQuantityUnit8 = outputQuantityUnit8;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>outputQuantityValue9</b></p>
     * 
     * @param outputQuantityValue9
     *     The outputQuantityValue9 to set.
     */
    public void setOutputQuantityValue9(
        @Nullable
        final BigDecimal outputQuantityValue9) {
        rememberChangedField("outputQuantityValue9", this.outputQuantityValue9);
        this.outputQuantityValue9 = outputQuantityValue9;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>outputQuantityUnit9</b></p>
     * 
     * @param outputQuantityUnit9
     *     The outputQuantityUnit9 to set.
     */
    public void setOutputQuantityUnit9(
        @Nullable
        final java.lang.String outputQuantityUnit9) {
        rememberChangedField("outputQuantityUnit9", this.outputQuantityUnit9);
        this.outputQuantityUnit9 = outputQuantityUnit9;
    }

    /**
     * Constraints: Nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>priceConditionType</b></p>
     * 
     * @param priceConditionType
     *     The priceConditionType to set.
     */
    public void setPriceConditionType(
        @Nullable
        final java.lang.String priceConditionType) {
        rememberChangedField("priceConditionType", this.priceConditionType);
        this.priceConditionType = priceConditionType;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>priceConditionMonetaryAmountCurrency</b></p>
     * 
     * @param priceConditionMonetaryAmountCurrency
     *     The priceConditionMonetaryAmountCurrency to set.
     */
    public void setPriceConditionMonetaryAmountCurrency(
        @Nullable
        final java.lang.String priceConditionMonetaryAmountCurrency) {
        rememberChangedField("priceConditionMonetaryAmountCurrency", this.priceConditionMonetaryAmountCurrency);
        this.priceConditionMonetaryAmountCurrency = priceConditionMonetaryAmountCurrency;
    }

    /**
     * Constraints: Nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>lookupTable_code</b></p>
     * 
     * @param lookupTable_code
     *     The lookupTable_code to set.
     */
    public void setLookupTable_code(
        @Nullable
        final java.lang.String lookupTable_code) {
        rememberChangedField("lookupTable_code", this.lookupTable_code);
        this.lookupTable_code = lookupTable_code;
    }

    /**
     * Constraints: Nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>operation</b></p>
     * 
     * @param operation
     *     The operation to set.
     */
    public void setOperation(
        @Nullable
        final java.lang.String operation) {
        rememberChangedField("operation", this.operation);
        this.operation = operation;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>priceConditionRanges</b></p>
     * 
     * @param priceConditionRanges
     *     The priceConditionRanges to set.
     */
    public void setPriceConditionRanges(
        @Nullable
        final java.util.Collection<com_sap_cloud_pricing_calculation_PriceConditionRange> priceConditionRanges) {
        rememberChangedField("priceConditionRanges", this.priceConditionRanges);
        this.priceConditionRanges = priceConditionRanges;
    }

}
