
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.namespaces.maintenancelookuptabledata;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.example.datamodel.odata.services.MaintenanceLookupTableDataService;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * <p>Original entity name from the Odata EDM: <b>LookupTables</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class LookupTables
    extends VdmEntity<LookupTables>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "MaintenanceLookupTableDataService.LookupTables";
    /**
     * Selector for all available fields of LookupTables.
     * 
     */
    public final static SimpleProperty<LookupTables> ALL_FIELDS = all();
    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>description</b></p>
     * 
     * @return
     *     Description
     */
    @Nullable
    @ElementName("description")
    private java.lang.String description;
    public final static SimpleProperty.String<LookupTables> DESCRIPTION = new SimpleProperty.String<LookupTables>(LookupTables.class, "description");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>code</b></p>
     * 
     * @return
     *     The code contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("code")
    private java.lang.String code;
    public final static SimpleProperty.String<LookupTables> CODE = new SimpleProperty.String<LookupTables>(LookupTables.class, "code");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @return
     *     The iD contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ID")
    private UUID iD;
    public final static SimpleProperty.Guid<LookupTables> ID = new SimpleProperty.Guid<LookupTables>(LookupTables.class, "ID");
    /**
     * Navigation property <b>inputs</b> for <b>LookupTables</b> to multiple <b>LookupTableInputs</b>.
     * 
     */
    @ElementName("inputs")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<LookupTableInputs> toInputs;
    /**
     * Navigation property <b>outputs</b> for <b>LookupTables</b> to multiple <b>LookupTableOutputs</b>.
     * 
     */
    @ElementName("outputs")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<LookupTableOutputs> toOutputs;
    /**
     * Use with available request builders to apply the <b>inputs</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<LookupTables, LookupTableInputs> TO_INPUTS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<LookupTables, LookupTableInputs>(LookupTables.class, "inputs", LookupTableInputs.class);
    /**
     * Use with available request builders to apply the <b>outputs</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<LookupTables, LookupTableOutputs> TO_OUTPUTS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<LookupTables, LookupTableOutputs>(LookupTables.class, "outputs", LookupTableOutputs.class);

    @Nonnull
    @Override
    public Class<LookupTables> getType() {
        return LookupTables.class;
    }

    /**
     * Constraints: Nullable, Maximum length: 2000 <p>Original property name from the Odata EDM: <b>description</b></p>
     * 
     * @param description
     *     Description
     */
    public void setDescription(
        @Nullable
        final java.lang.String description) {
        rememberChangedField("description", this.description);
        this.description = description;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>code</b></p>
     * 
     * @param code
     *     The code to set.
     */
    public void setCode(
        @Nullable
        final java.lang.String code) {
        rememberChangedField("code", this.code);
        this.code = code;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @param iD
     *     The iD to set.
     */
    public void setID(
        @Nullable
        final UUID iD) {
        rememberChangedField("ID", this.iD);
        this.iD = iD;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "LookupTables";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("code", getCode());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("description", getDescription());
        values.put("code", getCode());
        values.put("ID", getID());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("description")) {
                final Object value = values.remove("description");
                if ((value == null)||(!value.equals(getDescription()))) {
                    setDescription(((java.lang.String) value));
                }
            }
            if (values.containsKey("code")) {
                final Object value = values.remove("code");
                if ((value == null)||(!value.equals(getCode()))) {
                    setCode(((java.lang.String) value));
                }
            }
            if (values.containsKey("ID")) {
                final Object value = values.remove("ID");
                if ((value == null)||(!value.equals(getID()))) {
                    setID(((UUID) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((values).containsKey("inputs")) {
                final Object value = (values).remove("inputs");
                if (value instanceof Iterable) {
                    if (toInputs == null) {
                        toInputs = Lists.newArrayList();
                    } else {
                        toInputs = Lists.newArrayList(toInputs);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) value)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        LookupTableInputs entity;
                        if (toInputs.size()>i) {
                            entity = toInputs.get(i);
                        } else {
                            entity = new LookupTableInputs();
                            toInputs.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
            if ((values).containsKey("outputs")) {
                final Object value = (values).remove("outputs");
                if (value instanceof Iterable) {
                    if (toOutputs == null) {
                        toOutputs = Lists.newArrayList();
                    } else {
                        toOutputs = Lists.newArrayList(toOutputs);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) value)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        LookupTableOutputs entity;
                        if (toOutputs.size()>i) {
                            entity = toOutputs.get(i);
                        } else {
                            entity = new LookupTableOutputs();
                            toOutputs.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(values);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return MaintenanceLookupTableDataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> values = super.toMapOfNavigationProperties();
        if (toInputs!= null) {
            (values).put("inputs", toInputs);
        }
        if (toOutputs!= null) {
            (values).put("outputs", toOutputs);
        }
        return values;
    }

    /**
     * Retrieval of associated <b>LookupTableInputs</b> entities (one to many). This corresponds to the OData navigation property <b>inputs</b>.
     * <p>
     * If the navigation property for an entity <b>LookupTables</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>inputs</b> is already loaded, the result will contain the <b>LookupTableInputs</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<LookupTableInputs>> getInputsIfPresent() {
        return Option.of(toInputs);
    }

    /**
     * Overwrites the list of associated <b>LookupTableInputs</b> entities for the loaded navigation property <b>inputs</b>.
     * <p>
     * If the navigation property <b>inputs</b> of a queried <b>LookupTables</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param value
     *     List of <b>LookupTableInputs</b> entities.
     */
    public void setInputs(
        @Nonnull
        final List<LookupTableInputs> value) {
        if (toInputs == null) {
            toInputs = Lists.newArrayList();
        }
        toInputs.clear();
        toInputs.addAll(value);
    }

    /**
     * Adds elements to the list of associated <b>LookupTableInputs</b> entities. This corresponds to the OData navigation property <b>inputs</b>.
     * <p>
     * If the navigation property <b>inputs</b> of a queried <b>LookupTables</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>LookupTableInputs</b> entities.
     */
    public void addInputs(LookupTableInputs... entity) {
        if (toInputs == null) {
            toInputs = Lists.newArrayList();
        }
        toInputs.addAll(Lists.newArrayList(entity));
    }

    /**
     * Retrieval of associated <b>LookupTableOutputs</b> entities (one to many). This corresponds to the OData navigation property <b>outputs</b>.
     * <p>
     * If the navigation property for an entity <b>LookupTables</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>outputs</b> is already loaded, the result will contain the <b>LookupTableOutputs</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<LookupTableOutputs>> getOutputsIfPresent() {
        return Option.of(toOutputs);
    }

    /**
     * Overwrites the list of associated <b>LookupTableOutputs</b> entities for the loaded navigation property <b>outputs</b>.
     * <p>
     * If the navigation property <b>outputs</b> of a queried <b>LookupTables</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param value
     *     List of <b>LookupTableOutputs</b> entities.
     */
    public void setOutputs(
        @Nonnull
        final List<LookupTableOutputs> value) {
        if (toOutputs == null) {
            toOutputs = Lists.newArrayList();
        }
        toOutputs.clear();
        toOutputs.addAll(value);
    }

    /**
     * Adds elements to the list of associated <b>LookupTableOutputs</b> entities. This corresponds to the OData navigation property <b>outputs</b>.
     * <p>
     * If the navigation property <b>outputs</b> of a queried <b>LookupTables</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>LookupTableOutputs</b> entities.
     */
    public void addOutputs(LookupTableOutputs... entity) {
        if (toOutputs == null) {
            toOutputs = Lists.newArrayList();
        }
        toOutputs.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of LookupTables instances.
     * 
     */
    public final static class LookupTablesBuilder {

        private List<LookupTableInputs> toInputs = Lists.newArrayList();
        private List<LookupTableOutputs> toOutputs = Lists.newArrayList();

        private LookupTables.LookupTablesBuilder toInputs(final List<LookupTableInputs> value) {
            toInputs.addAll(value);
            return this;
        }

        /**
         * Navigation property <b>inputs</b> for <b>LookupTables</b> to multiple <b>LookupTableInputs</b>.
         * 
         * @param value
         *     The LookupTableInputss to build this LookupTables with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public LookupTables.LookupTablesBuilder inputs(LookupTableInputs... value) {
            return toInputs(Lists.newArrayList(value));
        }

        private LookupTables.LookupTablesBuilder toOutputs(final List<LookupTableOutputs> value) {
            toOutputs.addAll(value);
            return this;
        }

        /**
         * Navigation property <b>outputs</b> for <b>LookupTables</b> to multiple <b>LookupTableOutputs</b>.
         * 
         * @param value
         *     The LookupTableOutputss to build this LookupTables with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public LookupTables.LookupTablesBuilder outputs(LookupTableOutputs... value) {
            return toOutputs(Lists.newArrayList(value));
        }

    }

}
