
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.6.0
 */

package com.example.datamodel.odata.namespaces.maintenancelookuptabledata;

import java.math.BigDecimal;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.example.datamodel.odata.services.MaintenanceLookupTableDataService;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.DecimalDescriptor;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original entity name from the Odata EDM: <b>PriceConditionRanges</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class PriceConditionRanges
    extends VdmEntity<PriceConditionRanges>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "MaintenanceLookupTableDataService.PriceConditionRanges";
    /**
     * Selector for all available fields of PriceConditionRanges.
     * 
     */
    public final static SimpleProperty<PriceConditionRanges> ALL_FIELDS = all();
    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>type</b></p>
     * 
     * @return
     *     The type_2 contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("type")
    private java.lang.String type_2;
    public final static SimpleProperty.String<PriceConditionRanges> TYPE_2 = new SimpleProperty.String<PriceConditionRanges>(PriceConditionRanges.class, "type");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>value</b></p>
     * 
     * @return
     *     The monetary amount value of the price or the multiplier value to apply in case of Percentage pricing
     */
    @Nullable
    @ElementName("value")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal value;
    public final static SimpleProperty.NumericDecimal<PriceConditionRanges> VALUE = new SimpleProperty.NumericDecimal<PriceConditionRanges>(PriceConditionRanges.class, "value");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>rateQuantity</b></p>
     * 
     * @return
     *     The rateQuantity contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("rateQuantity")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal rateQuantity;
    public final static SimpleProperty.NumericDecimal<PriceConditionRanges> RATE_QUANTITY = new SimpleProperty.NumericDecimal<PriceConditionRanges>(PriceConditionRanges.class, "rateQuantity");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>rateQuantityUnit</b></p>
     * 
     * @return
     *     The rateQuantityUnit contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("rateQuantityUnit")
    private java.lang.String rateQuantityUnit;
    public final static SimpleProperty.String<PriceConditionRanges> RATE_QUANTITY_UNIT = new SimpleProperty.String<PriceConditionRanges>(PriceConditionRanges.class, "rateQuantityUnit");
    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>upToValue</b></p>
     * 
     * @return
     *     The upToValue contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("upToValue")
    @DecimalDescriptor(precision = 22, scale = 6)
    private BigDecimal upToValue;
    public final static SimpleProperty.NumericDecimal<PriceConditionRanges> UP_TO_VALUE = new SimpleProperty.NumericDecimal<PriceConditionRanges>(PriceConditionRanges.class, "upToValue");
    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>upToUnit</b></p>
     * 
     * @return
     *     The upToUnit contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("upToUnit")
    private java.lang.String upToUnit;
    public final static SimpleProperty.String<PriceConditionRanges> UP_TO_UNIT = new SimpleProperty.String<PriceConditionRanges>(PriceConditionRanges.class, "upToUnit");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>row_ID</b></p>
     * 
     * @return
     *     The row_ID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("row_ID")
    private UUID row_ID;
    public final static SimpleProperty.Guid<PriceConditionRanges> ROW_ID = new SimpleProperty.Guid<PriceConditionRanges>(PriceConditionRanges.class, "row_ID");

    @Nonnull
    @Override
    public Class<PriceConditionRanges> getType() {
        return PriceConditionRanges.class;
    }

    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>type</b></p>
     * 
     * @param type_2
     *     The type_2 to set.
     */
    public void setType_2(
        @Nullable
        final java.lang.String type_2) {
        rememberChangedField("type", this.type_2);
        this.type_2 = type_2;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>value</b></p>
     * 
     * @param value
     *     The monetary amount value of the price or the multiplier value to apply in case of Percentage pricing
     */
    public void setValue(
        @Nullable
        final BigDecimal value) {
        rememberChangedField("value", this.value);
        this.value = value;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>rateQuantity</b></p>
     * 
     * @param rateQuantity
     *     The rateQuantity to set.
     */
    public void setRateQuantity(
        @Nullable
        final BigDecimal rateQuantity) {
        rememberChangedField("rateQuantity", this.rateQuantity);
        this.rateQuantity = rateQuantity;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>rateQuantityUnit</b></p>
     * 
     * @param rateQuantityUnit
     *     The rateQuantityUnit to set.
     */
    public void setRateQuantityUnit(
        @Nullable
        final java.lang.String rateQuantityUnit) {
        rememberChangedField("rateQuantityUnit", this.rateQuantityUnit);
        this.rateQuantityUnit = rateQuantityUnit;
    }

    /**
     * Constraints: Nullable, Precision: 22, Scale: 6 <p>Original property name from the Odata EDM: <b>upToValue</b></p>
     * 
     * @param upToValue
     *     The upToValue to set.
     */
    public void setUpToValue(
        @Nullable
        final BigDecimal upToValue) {
        rememberChangedField("upToValue", this.upToValue);
        this.upToValue = upToValue;
    }

    /**
     * Constraints: Nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>upToUnit</b></p>
     * 
     * @param upToUnit
     *     The upToUnit to set.
     */
    public void setUpToUnit(
        @Nullable
        final java.lang.String upToUnit) {
        rememberChangedField("upToUnit", this.upToUnit);
        this.upToUnit = upToUnit;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>row_ID</b></p>
     * 
     * @param row_ID
     *     The row_ID to set.
     */
    public void setRow_ID(
        @Nullable
        final UUID row_ID) {
        rememberChangedField("row_ID", this.row_ID);
        this.row_ID = row_ID;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "PriceConditionRanges";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("type", getType_2());
        values.put("value", getValue());
        values.put("rateQuantity", getRateQuantity());
        values.put("rateQuantityUnit", getRateQuantityUnit());
        values.put("upToValue", getUpToValue());
        values.put("upToUnit", getUpToUnit());
        values.put("row_ID", getRow_ID());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("type")) {
                final Object value = values.remove("type");
                if ((value == null)||(!value.equals(getType_2()))) {
                    setType_2(((java.lang.String) value));
                }
            }
            if (values.containsKey("value")) {
                final Object value = values.remove("value");
                if ((value == null)||(!value.equals(getValue()))) {
                    setValue(((BigDecimal) value));
                }
            }
            if (values.containsKey("rateQuantity")) {
                final Object value = values.remove("rateQuantity");
                if ((value == null)||(!value.equals(getRateQuantity()))) {
                    setRateQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("rateQuantityUnit")) {
                final Object value = values.remove("rateQuantityUnit");
                if ((value == null)||(!value.equals(getRateQuantityUnit()))) {
                    setRateQuantityUnit(((java.lang.String) value));
                }
            }
            if (values.containsKey("upToValue")) {
                final Object value = values.remove("upToValue");
                if ((value == null)||(!value.equals(getUpToValue()))) {
                    setUpToValue(((BigDecimal) value));
                }
            }
            if (values.containsKey("upToUnit")) {
                final Object value = values.remove("upToUnit");
                if ((value == null)||(!value.equals(getUpToUnit()))) {
                    setUpToUnit(((java.lang.String) value));
                }
            }
            if (values.containsKey("row_ID")) {
                final Object value = values.remove("row_ID");
                if ((value == null)||(!value.equals(getRow_ID()))) {
                    setRow_ID(((UUID) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return MaintenanceLookupTableDataService.DEFAULT_SERVICE_PATH;
    }

}
