
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.3.0
 */

package vdm.com.example.datamodel.odata.services;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder;
import vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>UnitofMeasurement</td></tr></table>
 * 
 */
public interface UnitofMeasurementService {

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "odata/v4/MasterDataService";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    UnitofMeasurementService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Creates a batch request builder object.
     * 
     * @return
     *     A request builder to handle batch operation on this service. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder>#execute(Destination) execute} method on the request builder object.
     */
    @Nonnull
    BatchRequestBuilder batch();

    /**
     * Fetch multiple {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entities.
     *
     * @return
     *     A request builder to fetch multiple {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    GetAllRequestBuilder<UnitOfMeasures> getAllUnitOfMeasures();

    /**
     * Fetch the number of entries from the {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    CountRequestBuilder<UnitOfMeasures> countUnitOfMeasures();

    /**
     * Fetch a single {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity using key fields.
     * 
     * @param code
     *     <p>Constraints: Not nullable</p>
     * @return
     *     A request builder to fetch a single {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    GetByKeyRequestBuilder<UnitOfMeasures> getUnitOfMeasuresByKey(final String code);

    /**
     * Create a new {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity and save it to the S/4HANA system.
     * 
     * @param unitOfMeasures
     *     {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity object that will be created in the S/4HANA system.
     * @return
     *     A request builder to create a new {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    CreateRequestBuilder<UnitOfMeasures> createUnitOfMeasures(
        @Nonnull
        final UnitOfMeasures unitOfMeasures);

    /**
     * Update an existing {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity and save it to the S/4HANA system.
     * 
     * @param unitOfMeasures
     *     {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    UpdateRequestBuilder<UnitOfMeasures> updateUnitOfMeasures(
        @Nonnull
        final UnitOfMeasures unitOfMeasures);

    /**
     * Deletes an existing {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity in the S/4HANA system.
     * 
     * @param unitOfMeasures
     *     {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures UnitOfMeasures} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<vdm.com.example.datamodel.odata.namespaces.unitofmeasurement.UnitOfMeasures>#execute execute} method on the request builder object.
     */
    @Nonnull
    DeleteRequestBuilder<UnitOfMeasures> deleteUnitOfMeasures(
        @Nonnull
        final UnitOfMeasures unitOfMeasures);

}
